
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ariyan
 */
public class Admin extends javax.swing.JFrame {
    private BOOKS books;
    private Trusts trusts;
    private Create admincreate ;
    private AddBook addbook ;
    private Submitbook submit ;
    private static Trusts tr;

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu7 = new javax.swing.JMenu();
        afzodandaneshjo = new javax.swing.JButton();
        afzodanketab = new javax.swing.JButton();
        listketab = new javax.swing.JButton();
        kotobamanti = new javax.swing.JButton();
        sabtamanat = new javax.swing.JButton();
        sabterjaketab = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenuItem1.setText("jMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        jMenu7.setText("jMenu7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("مدیر");
        setResizable(false);

        afzodandaneshjo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        afzodandaneshjo.setText("افزودن دانشجو");
        afzodandaneshjo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        afzodandaneshjo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afzodandaneshjoActionPerformed(evt);
            }
        });

        afzodanketab.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        afzodanketab.setText("افزودن کتاب");
        afzodanketab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        afzodanketab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afzodanketabActionPerformed(evt);
            }
        });

        listketab.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        listketab.setText("لیست کتاب ها");
        listketab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listketab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listketabActionPerformed(evt);
            }
        });

        kotobamanti.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        kotobamanti.setText("نمایش کتب به امانت گرفته شده");
        kotobamanti.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kotobamanti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kotobamantiActionPerformed(evt);
            }
        });

        sabtamanat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sabtamanat.setText("ثبت امانت");
        sabtamanat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sabtamanat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sabtamanatActionPerformed(evt);
            }
        });

        sabterjaketab.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sabterjaketab.setText("ثبت برگرداندن امانت");
        sabterjaketab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sabterjaketab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sabterjaketabActionPerformed(evt);
            }
        });

        jToolBar1.setRollover(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(afzodandaneshjo, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(afzodanketab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listketab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sabterjaketab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kotobamanti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sabtamanat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(192, 192, 192))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(afzodandaneshjo)
                .addGap(35, 35, 35)
                .addComponent(afzodanketab)
                .addGap(35, 35, 35)
                .addComponent(listketab)
                .addGap(35, 35, 35)
                .addComponent(kotobamanti)
                .addGap(35, 35, 35)
                .addComponent(sabtamanat)
                .addGap(35, 35, 35)
                .addComponent(sabterjaketab)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kotobamantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kotobamantiActionPerformed
        trusts = new Trusts();
        try {
            trusts.initComponent();
        } catch (IOException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_kotobamantiActionPerformed

    private void sabterjaketabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sabterjaketabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sabterjaketabActionPerformed

    private void afzodanketabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afzodanketabActionPerformed
        addbook = new AddBook();
        addbook.setVisible(true);           
    }//GEN-LAST:event_afzodanketabActionPerformed

    private void afzodandaneshjoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afzodandaneshjoActionPerformed
        admincreate = new Create();
        admincreate.setVisible(true);   
    }//GEN-LAST:event_afzodandaneshjoActionPerformed

    private void listketabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listketabActionPerformed
        books = new BOOKS();
        try {
            books.initComponent();
        } catch (IOException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_listketabActionPerformed

    private void sabtamanatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sabtamanatActionPerformed
        submit = new Submitbook();
        submit.setVisible(true);
    }//GEN-LAST:event_sabtamanatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton afzodandaneshjo;
    private javax.swing.JButton afzodanketab;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton kotobamanti;
    private javax.swing.JButton listketab;
    private javax.swing.JButton sabtamanat;
    private javax.swing.JButton sabterjaketab;
    // End of variables declaration//GEN-END:variables
}
